// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// projects.js
export const RETRIEVE_PROJECTS = 'RETRIEVE_PROJECTS'
export const RETRIEVE_PROJECT = 'RETRIEVE_PROJECT'
export const ADD_PROJECT = 'ADD_PROJECT'
export const UPDATE_PROJECTS_FILTER = 'UPDATE_PROJECTS_FILTER'
export const UPDATE_USER_FILTER = 'UPDATE_USER_FILTER'
export const UPDATE_DATE_FILTER = 'UPDATE_DATE_FILTER'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

// categories.js
export const RETRIEVE_CATEGORIES = 'RETRIEVE_CATEGORIES'

// users.js
export const RETRIEVE_USERS = 'RETRIEVE_USERS'

// games.js
export const RETRIEVE_GAMES = 'RETRIEVE_GAMES'
export const RETRIEVE_PLAYERS = 'RETRIEVE_PLAYERS'
export const UPDATE_GAMES_FILTER = 'UPDATE_GAMES_FILTER'

// ranking.js
export const RETRIEVE_TOP_PROJECTS = 'RETRIEVE_TOP_PROJECTS'
export const UPDATE_RANKING_FILTER = 'UPDATE_RANKING_FILTER'
